#!/bin/bash

aws ec2 run-instances              \
  --image-id ami-0a0195724f881b811 \
  --instance-type t2.micro         \
  --region us-west-2               \
  --key-name rdeforest             \
  --security-group-ids sg-09a573677923495f3
