#!/bin/bash

aws ec2 run-instances              \
  --image-id ami-031ab6a89f1fa4ee8 \
  --instance-type t3.micro         \
  --region us-west-2               \
  --key-name rdeforest             \
  --security-group-ids sg-09a573677923495f3
