#!/bin/bash

aws ec2 run-instances              \
  --image-id ami-03a3c3aebfb1434b4 \
  --instance-type t3.micro         \
  --region us-west-2               \
  --key-name rdeforest             \
  --security-group-ids sg-09a573677923495f3
