// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee
  var Builder, Configurator, PermissionsChecker, State, Uploader, VERSION, askYesNo, checkRequirements, execSync, existsSync, join, main, options, parseArgs, proc, readline, showHelp;

  ({parseArgs} = require('util'));

  ({existsSync} = require('fs'));

  ({execSync} = require('child_process'));

  ({join} = require('path'));

  readline = require('readline');

  Builder = require('./builder');

  Configurator = require('./configurator');

  Uploader = require('./uploader');

  State = require('./state');

  PermissionsChecker = require('./permissions');

  VERSION = '0.1.0';

  // Global process object - injected by caller for testability
  proc = null;

  // ========================================================================
  // CLI Configuration
  // ========================================================================
  options = {
    release: {
      type: 'string',
      short: 'r',
      description: 'Devuan release (chimaera, daedalus, excalibur)',
      default: 'excalibur'
    },
    arch: {
      type: 'string',
      short: 'a',
      description: 'Architecture (amd64, arm64)',
      default: 'amd64'
    },
    's3-bucket': {
      type: 'string',
      short: 'b',
      description: 'S3 bucket for AMI storage'
    },
    region: {
      type: 'string',
      description: 'AWS region',
      default: 'us-east-1'
    },
    name: {
      type: 'string',
      short: 'n',
      description: 'AMI name'
    },
    'disk-size': {
      type: 'string',
      description: 'Disk size in GB',
      default: '8'
    },
    'work-dir': {
      type: 'string',
      description: 'Working directory for build artifacts',
      default: '/tmp/devuan-ami'
    },
    resume: {
      type: 'boolean',
      description: 'Resume previous build without prompting'
    },
    help: {
      type: 'boolean',
      short: 'h',
      description: 'Show help'
    },
    version: {
      type: 'boolean',
      short: 'v',
      description: 'Show version'
    }
  };

  // ========================================================================
  // Helpers
  // ========================================================================
  askYesNo = function(question) {
    return new Promise(function(resolve) {
      var rl;
      rl = readline.createInterface({
        input: proc.stdin,
        output: proc.stdout
      });
      return rl.question(`${question} [y/N] `, function(answer) {
        var ref;
        rl.close();
        return resolve((ref = answer.toLowerCase()) === 'y' || ref === 'yes');
      });
    });
  };

  showHelp = function() {
    console.log(`devuan-ami v${VERSION}
Build Devuan AWS Machine Images (AMIs) for EC2

Usage:
  devuan-ami [options]

Options:
  -r, --release <name>      Devuan release (default: excalibur)
  -a, --arch <arch>         Architecture: amd64, arm64 (default: amd64)
  -b, --s3-bucket <bucket>  S3 bucket for AMI storage (required)
      --region <region>     AWS region (default: us-east-1)
  -n, --name <name>         AMI name (auto-generated if not specified)
      --disk-size <gb>      Disk size in GB (default: 8)
      --work-dir <path>     Work directory (default: /tmp/devuan-ami)
      --resume              Resume previous build without prompting
  -h, --help                Show this help
  -v, --version             Show version

Example:
  sudo devuan-ami --release excalibur --s3-bucket my-bucket --name "Devuan Excalibur"

Requirements:
  - Must run as root
  - Requires: debootstrap, qemu-utils, awscli, parted`);
    return proc.exit(0);
  };

  checkRequirements = function() {
    var cmd, i, len, required, results;
    // Check root
    if (proc.getuid() !== 0) {
      console.error('Error: Must run as root (use sudo)');
      proc.exit(1);
    }
    // Check required commands
    required = ['debootstrap', 'qemu-img', 'aws', 'parted', 'losetup'];
    results = [];
    for (i = 0, len = required.length; i < len; i++) {
      cmd = required[i];
      try {
        results.push(execSync(`which ${cmd}`, {
          stdio: 'ignore'
        }));
      } catch (error1) {
        console.error(`Error: Required command not found: ${cmd}`);
        console.error("Install with: apt-get install debootstrap qemu-utils awscli parted");
        results.push(proc.exit(1));
      }
    }
    return results;
  };

  // ========================================================================
  // Main
  // ========================================================================
  main = async function(processObj = process) {
    var amiId, builder, configurator, error, imagePath, key, now, permChecker, positionals, progress, ref, ref1, savedState, shouldResume, state, timestamp, uploader, value, values;
    // Inject process for testability
    proc = processObj;
    // Parse arguments
    ({values, positionals} = parseArgs({
      args: proc.argv.slice(2),
      options: options,
      allowPositionals: true
    }));
    // Handle positional commands
    if (((ref = positionals[0]) === 'help' || ref === '--help' || ref === '-h') || values.help) {
      showHelp();
    }
    if (((ref1 = positionals[0]) === 'version' || ref1 === '--version' || ref1 === '-v') || values.version) {
      console.log(VERSION);
      proc.exit(0);
    }
    // Load state early for resume functionality
    state = new State(values['work-dir']);
    if (values.resume) {
      if (state.exists()) {
        savedState = state.load();
// Merge saved options with command line (command line takes precedence)
// But only override if value wasn't explicitly provided on command line
        for (key in savedState) {
          value = savedState[key];
          if (key !== 'completed') {
            // Skip if user explicitly provided this arg (check against defaults)
            if (key === 'region' && !proc.argv.includes('--region')) {
              values[key] = value;
            } else if (key === 'release' && !proc.argv.includes('--release') && !proc.argv.includes('-r')) {
              values[key] = value;
            } else if (key === 'arch' && !proc.argv.includes('--arch') && !proc.argv.includes('-a')) {
              values[key] = value;
            } else if (key === 'disk-size' && !proc.argv.includes('--disk-size')) {
              values[key] = value;
            } else if (key !== 'region' && key !== 'release' && key !== 'arch' && key !== 'disk-size') {
              if (values[key] == null) {
                values[key] = value;
              }
            }
          }
        }
      } else {
        console.error(`Error: --resume specified but no previous build found in ${values['work-dir']}`);
        proc.exit(1);
      }
    }
    // Validate required options
    if (!values['s3-bucket']) {
      console.error('Error: --s3-bucket is required');
      proc.exit(1);
    }
    // Check system requirements
    checkRequirements();
    // Check AWS permissions
    permChecker = new PermissionsChecker(values['s3-bucket'], values.region);
    if (!permChecker.check()) {
      proc.exit(1);
    }
    // Generate AMI name if not provided
    if (!values.name) {
      // Include time to avoid conflicts when building multiple times per day
      now = new Date();
      timestamp = now.toISOString().replace(/[:.]/g, '-').slice(0, -5); // 2025-10-28T12-34-56
      values.name = `Devuan-${values.release}-${values.arch}-${timestamp}`;
    }
    // Check for previous build (state already created above if --resume)
    if (state.exists()) {
      progress = state.detectProgress();
      if (values.resume) {
        console.log("Resuming previous build...");
        state.load();
      } else {
        console.log(`Found previous build in ${values['work-dir']}:`);
        console.log(`  Disk image built:  ${progress.built ? '✓' : '✗'}`);
        console.log(`  System configured: ${progress.configured ? '✓' : '✗'}`);
        console.log(`  Converted to VMDK: ${progress.converted ? '✓' : '✗'}`);
        console.log("");
        shouldResume = (await askYesNo("Resume from previous build?"));
        if (!shouldResume) {
          console.log(`Please remove ${values['work-dir']} or use a different --work-dir`);
          proc.exit(1);
        }
        state.load();
      }
    }
    // Save options for future resume
    state.saveOptions(values);
    console.log(`Building Devuan AMI: ${values.name}`);
    console.log(`  Release:    ${values.release}`);
    console.log(`  Arch:       ${values.arch}`);
    console.log(`  Disk size:  ${values['disk-size']}GB`);
    console.log(`  Work dir:   ${values['work-dir']}`);
    console.log(`  S3 bucket:  ${values['s3-bucket']}`);
    console.log(`  Region:     ${values.region}`);
    console.log("");
    try {
      // Build pipeline
      progress = state.detectProgress();
      // 1. Create disk image with debootstrap
      if (!progress.built) {
        console.log("Step 1/3: Building disk image...");
        builder = new Builder(values);
        imagePath = builder.build();
        state.complete('build');
      } else {
        console.log("Step 1/3: Building disk image... (skipped, already done)");
        imagePath = join(values['work-dir'], 'disk.raw');
      }
      // 2. Configure system for AWS
      if (!progress.configured) {
        console.log("\nStep 2/3: Configuring for AWS...");
        configurator = new Configurator(values, imagePath);
        configurator.configure();
        state.complete('configure');
      } else {
        console.log("\nStep 2/3: Configuring for AWS... (skipped, already done)");
      }
      // 3. Upload and register AMI
      console.log("\nStep 3/3: Uploading to AWS...");
      uploader = new Uploader(values, imagePath, state);
      amiId = uploader.upload();
      console.log("\n✓ AMI created successfully!");
      console.log(`  AMI ID: ${amiId}`);
      return console.log(`  Region: ${values.region}`);
    } catch (error1) {
      error = error1;
      console.error(`\n✗ Build failed: ${error.message}`);
      console.error("You can resume with: sudo bin/devuan-ami --resume");
      return proc.exit(1);
    }
  };

  // Export for testing, run if called directly
  module.exports = main;

  if (require.main === module) {
    main();
  }

}).call(this);
