// Generated by CoffeeScript 2.7.0
(function() {
  var Builder, MIRRORS, execSync, join, mkdirSync, readFileSync;

  ({execSync} = require('child_process'));

  ({mkdirSync} = require('fs'));

  ({readFileSync} = require('fs'));

  ({join} = require('path'));

  // ========================================================================
  // Devuan Mirror Configuration
  // ========================================================================
  MIRRORS = {
    default: 'http://deb.devuan.org/merged',
    pkgmaster: 'http://pkgmaster.devuan.org/merged'
  };

  // ========================================================================
  // Builder Class
  // ========================================================================
  Builder = class Builder {
    constructor(opts) {
      this.opts = opts;
      this.workDir = this.opts['work-dir'];
      this.imagePath = join(this.workDir, 'disk.raw');
      this.mountDir = join(this.workDir, 'mnt');
      this.loopDev = null;
    }

    // ====================================================================
    // Main Build Process
    // ====================================================================
    build() {
      this.createWorkspace();
      this.createDiskImage();
      this.setupLoopDevice();
      this.partitionDisk();
      this.createFilesystem();
      this.mountFilesystem();
      this.runDebootstrap();
      this.cleanup();
      return this.imagePath;
    }

    // ====================================================================
    // Build Steps
    // ====================================================================
    createWorkspace() {
      console.log(`  Creating workspace: ${this.workDir}`);
      execSync(`mkdir -p ${this.workDir}`);
      return execSync(`mkdir -p ${this.mountDir}`);
    }

    createDiskImage() {
      var sizeGB;
      sizeGB = this.opts['disk-size'];
      console.log(`  Creating ${sizeGB}GB disk image...`);
      return execSync(`qemu-img create -f raw ${this.imagePath} ${sizeGB}G`);
    }

    setupLoopDevice() {
      var output;
      console.log("  Setting up loop device...");
      output = execSync(`losetup --find --show --partscan ${this.imagePath}`);
      this.loopDev = output.toString().trim();
      return console.log(`  Loop device: ${this.loopDev}`);
    }

    partitionDisk() {
      var cmd, commands, i, len;
      console.log("  Partitioning disk...");
      // Create single partition for root
      commands = [`parted -s ${this.loopDev} mklabel msdos`, `parted -s ${this.loopDev} mkpart primary ext4 1MiB 100%`, `parted -s ${this.loopDev} set 1 boot on`];
      for (i = 0, len = commands.length; i < len; i++) {
        cmd = commands[i];
        execSync(cmd);
      }
      // Inform kernel of partition changes
      return execSync(`partprobe ${this.loopDev}`);
    }

    createFilesystem() {
      var partition;
      partition = `${this.loopDev}p1`;
      console.log(`  Creating ext4 filesystem on ${partition}...`);
      return execSync(`mkfs.ext4 -L devuan-root ${partition}`);
    }

    mountFilesystem() {
      var partition;
      partition = `${this.loopDev}p1`;
      console.log("  Mounting filesystem...");
      return execSync(`mount ${partition} ${this.mountDir}`);
    }

    runDebootstrap() {
      var arch, cmd, configPath, content, error, mirror, packageList, packages, release;
      ({release, arch} = this.opts);
      mirror = MIRRORS.default;
      console.log("  Running debootstrap (this may take several minutes)...");
      console.log(`    Release: ${release}`);
      console.log(`    Arch:    ${arch}`);
      console.log(`    Mirror:  ${mirror}`);
      // Load package list from config file
      configPath = join(__dirname, '../config/packages.txt');
      content = readFileSync(configPath, 'utf8');
      // Parse: one package per line, ignore comments and blank lines
      packages = content.split('\n').map(function(line) {
        return line.trim();
      }).filter(function(line) {
        return line && !line.startsWith('#');
      });
      packageList = packages.join(',');
      console.log(`    Packages: ${packages.length} packages`);
      cmd = `debootstrap --variant=minbase --arch=${arch} --include=${packageList} ${release} ${this.mountDir} ${mirror}`;
      try {
        return execSync(cmd, {
          stdio: 'inherit'
        });
      } catch (error1) {
        error = error1;
        throw new Error(`debootstrap failed: ${error.message}`);
      }
    }

    cleanup() {
      var error;
      console.log("  Unmounting and cleaning up...");
      try {
        // Unmount filesystem
        execSync(`umount ${this.mountDir}`);
      } catch (error1) {
        error = error1;
        console.warn(`Warning: Failed to unmount ${this.mountDir}`);
      }
      // Detach loop device
      if (this.loopDev) {
        try {
          return execSync(`losetup -d ${this.loopDev}`);
        } catch (error1) {
          error = error1;
          return console.warn(`Warning: Failed to detach loop device ${this.loopDev}`);
        }
      }
    }

  };

  module.exports = Builder;

}).call(this);
