// Generated by CoffeeScript 2.7.0
(function() {
  var Configurator, execSync, join, writeFileSync;

  ({execSync} = require('child_process'));

  ({writeFileSync} = require('fs'));

  ({join} = require('path'));

  // ========================================================================
  // Configurator Class
  // ========================================================================
  Configurator = class Configurator {
    constructor(opts, imagePath) {
      this.opts = opts;
      this.imagePath = imagePath;
      this.workDir = this.opts['work-dir'];
      this.mountDir = join(this.workDir, 'mnt');
      this.loopDev = null;
    }

    // ====================================================================
    // Main Configuration Process
    // ====================================================================
    configure() {
      this.mountImage();
      this.mountPseudoFilesystems();
      this.configureFstab();
      this.configureNetwork();
      this.configureLocale();
      this.configureCloudInit();
      this.installGrub();
      this.configureSSH();
      this.createAdminUser();
      this.configureSerialConsole();
      this.cleanupSystem();
      return this.unmountAll();
    }

    // ====================================================================
    // Filesystem Management
    // ====================================================================
    mountImage() {
      var output, partition;
      console.log("  Mounting disk image...");
      output = execSync(`losetup --find --show --partscan ${this.imagePath}`);
      this.loopDev = output.toString().trim();
      partition = `${this.loopDev}p1`;
      return execSync(`mount ${partition} ${this.mountDir}`);
    }

    mountPseudoFilesystems() {
      console.log("  Mounting pseudo-filesystems for chroot...");
      execSync(`mount -t proc  proc  ${this.mountDir}/proc`);
      execSync(`mount -t sysfs sys   ${this.mountDir}/sys`);
      execSync(`mount -o bind  /dev  ${this.mountDir}/dev`);
      return execSync(`mount -t devpts devpts ${this.mountDir}/dev/pts`);
    }

    unmountAll() {
      var error, i, len, path, ref;
      console.log("  Unmounting all filesystems...");
      ref = ['/dev/pts', '/dev', '/sys', '/proc', ''];
      // Unmount in reverse order
      for (i = 0, len = ref.length; i < len; i++) {
        path = ref[i];
        try {
          execSync(`umount ${this.mountDir}${path}`);
        } catch (error1) {
          error = error1;
          console.warn(`Warning: Failed to unmount ${this.mountDir}${path}`);
        }
      }
      // Detach loop device
      if (this.loopDev) {
        try {
          return execSync(`losetup -d ${this.loopDev}`);
        } catch (error1) {
          error = error1;
          return console.warn(`Warning: Failed to detach ${this.loopDev}`);
        }
      }
    }

    // ====================================================================
    // Configuration Steps
    // ====================================================================
    configureFstab() {
      var fstab;
      console.log("  Configuring fstab...");
      fstab = `# /etc/fstab: static file system information
LABEL=devuan-root  /        ext4  defaults,discard  0  1
tmpfs              /tmp     tmpfs defaults,nodev,nosuid  0  0`;
      return this.writeFile('/etc/fstab', fstab);
    }

    configureNetwork() {
      var interfaces;
      console.log("  Configuring network (cloud-init managed)...");
      // Let cloud-init handle network configuration
      // Disable traditional /etc/network/interfaces management
      interfaces = `# Network configuration is managed by cloud-init
# See /etc/cloud/cloud.cfg.d/ for configuration
auto lo
iface lo inet loopback`;
      return this.writeFile('/etc/network/interfaces', interfaces);
    }

    configureLocale() {
      var localeDefault, localeGen;
      console.log("  Configuring locales...");
      // Enable en_US.UTF-8 locale
      localeGen = `# This file lists locales that you wish to have built. You can find a list
# of valid supported locales at /usr/share/i18n/SUPPORTED, and you can add
# user defined locales to /usr/local/share/i18n/SUPPORTED. If you change
# this file, you need to rerun locale-gen.

en_US.UTF-8 UTF-8`;
      this.writeFile('/etc/locale.gen', localeGen);
      // Generate locale
      this.chroot("locale-gen");
      // Set default locale
      localeDefault = `LANG=en_US.UTF-8`;
      return this.writeFile('/etc/default/locale', localeDefault);
    }

    configureCloudInit() {
      var cloudConfig;
      console.log("  Configuring cloud-init...");
      // AWS-specific cloud-init configuration
      cloudConfig = `datasource_list: [ Ec2, None ]
datasource:
  Ec2:
    strict_id: false
    timeout: 10
    max_wait: 30

# Preserve traditional network interface names (eth0, eth1, etc.)
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: false

# System info
system_info:
  default_user:
    name: admin
    groups: [adm, sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash

# Disable root login
disable_root: true

# Manage /etc/hosts
manage_etc_hosts: true

# Grow root partition to fill disk
growpart:
  mode: auto
  devices: ['/']

# Resize filesystem
resize_rootfs: true`;
      return this.writeFile('/etc/cloud/cloud.cfg.d/99-aws.cfg', cloudConfig);
    }

    installGrub() {
      var grubDefault;
      console.log("  Installing GRUB bootloader...");
      // Configure GRUB for AWS (serial console, no splash)
      grubDefault = `GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=Devuan
GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0,115200n8 nvme_core.io_timeout=4294967295"
GRUB_CMDLINE_LINUX=""
GRUB_TERMINAL="console serial"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"`;
      this.writeFile('/etc/default/grub', grubDefault);
      // Install GRUB to loop device
      this.chroot(`grub-install ${this.loopDev}`);
      return this.chroot("update-grub");
    }

    configureSSH() {
      var sshdConfig;
      console.log("  Configuring SSH...");
      // SSH daemon config for AWS
      sshdConfig = `# SSH daemon configuration for AWS
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server`;
      this.writeFile('/etc/ssh/sshd_config', sshdConfig);
      // Enable SSH service (SysVinit)
      this.chroot("update-rc.d ssh defaults");
      return this.chroot("update-rc.d ssh enable");
    }

    createAdminUser() {
      console.log("  Creating admin user...");
      // cloud-init will create the user, but we set up the group
      return this.chroot("groupadd -f admin");
    }

    configureSerialConsole() {
      var inittabEntry;
      console.log("  Configuring serial console...");
      // Enable getty on serial console for AWS
      // Add to /etc/inittab for SysVinit
      inittabEntry = "T0:23:respawn:/sbin/getty -L ttyS0 115200 vt100\n";
      return this.appendFile('/etc/inittab', inittabEntry);
    }

    cleanupSystem() {
      console.log("  Cleaning up system...");
      // Clean package cache
      this.chroot("apt-get clean");
      // Remove machine-id (will be regenerated on first boot)
      this.writeFile('/etc/machine-id', '');
      // Clear log files
      return this.chroot("find /var/log -type f -exec truncate -s 0 {} \\;");
    }

    // ====================================================================
    // Helpers
    // ====================================================================
    chroot(cmd) {
      return execSync(`LC_ALL=C chroot ${this.mountDir} /bin/bash -c '${cmd}'`);
    }

    writeFile(path, content) {
      var fullPath;
      fullPath = join(this.mountDir, path);
      return writeFileSync(fullPath, content);
    }

    appendFile(path, content) {
      var appendFileSync, fullPath;
      fullPath = join(this.mountDir, path);
      ({appendFileSync} = require('fs'));
      return appendFileSync(fullPath, content);
    }

    hasSystemd() {
      // Devuan uses SysVinit by default, not systemd
      // Return false for now; we'll use traditional init scripts
      return false;
    }

  };

  module.exports = Configurator;

}).call(this);
