// Generated by CoffeeScript 2.7.0
(function() {
  var PermissionsChecker, execSync;

  ({execSync} = require('child_process'));

  // ========================================================================
  // AWS Permissions Checker
  // ========================================================================
  PermissionsChecker = class PermissionsChecker {
    constructor(bucket, region) {
      this.bucket = bucket;
      this.region = region;
      this.errors = [];
    }

    check() {
      var error, i, len, ref;
      console.log("Checking AWS permissions...");
      this.checkVmimportRole();
      this.checkS3Access();
      this.checkEC2Permissions();
      if (this.errors.length > 0) {
        console.error("\n✗ AWS permissions check failed:\n");
        ref = this.errors;
        for (i = 0, len = ref.length; i < len; i++) {
          error = ref[i];
          console.error(`  • ${error}`);
        }
        console.error("\nPlease fix these issues before continuing.\n");
        return false;
      }
      console.log("  ✓ All AWS permissions verified\n");
      return true;
    }

    checkVmimportRole() {
      var error;
      try {
        return execSync("aws iam get-role --role-name vmimport", {
          stdio: 'pipe'
        });
      } catch (error1) {
        error = error1;
        this.errors.push("vmimport IAM role does not exist");
        this.errors.push("  Fix: See docs/vmimport-setup.md");
        return this.errors.push(`       (Remember to replace YOUR-BUCKET-NAME with: ${this.bucket})`);
      }
    }

    checkS3Access() {
      var error, testFile;
      try {
        // Check if bucket exists and is accessible
        execSync(`aws s3 ls s3://${this.bucket} --region ${this.region}`, {
          stdio: 'pipe'
        });
      } catch (error1) {
        error = error1;
        this.errors.push(`Cannot access S3 bucket: s3://${this.bucket}`);
        this.errors.push("  Either the bucket doesn't exist or you lack permissions");
        this.errors.push(`  Create it with: aws s3 mb s3://${this.bucket} --region ${this.region}`);
      }
      try {
        // Check write permissions
        testFile = `s3://${this.bucket}/.permissions-test-${Date.now()}`;
        execSync(`echo test | aws s3 cp - ${testFile} --region ${this.region}`, {
          stdio: 'pipe'
        });
        return execSync(`aws s3 rm ${testFile} --region ${this.region}`, {
          stdio: 'pipe'
        });
      } catch (error1) {
        error = error1;
        this.errors.push(`Cannot write to S3 bucket: s3://${this.bucket}`);
        return this.errors.push("  Check your IAM permissions include s3:PutObject and s3:DeleteObject");
      }
    }

    checkEC2Permissions() {
      var error, result, user, userName;
      try {
        // Check basic EC2 describe permissions
        execSync(`aws ec2 describe-regions --region ${this.region}`, {
          stdio: 'pipe'
        });
      } catch (error1) {
        error = error1;
        this.errors.push(`Cannot access EC2 API in region ${this.region}`);
        this.errors.push("  Check your AWS credentials and region settings");
      }
      try {
        // Check import-snapshot permission
        // We can't actually test this without doing an import, so check IAM policies
        result = execSync("aws iam get-user", {
          encoding: 'utf8'
        });
        user = JSON.parse(result).User;
        userName = user.UserName;
        try {
          // Try to check attached policies
          return execSync(`aws iam list-attached-user-policies --user-name ${userName}`, {
            stdio: 'pipe'
          });
        } catch (error1) {

        }
      } catch (error1) {
        // User might have group policies or inline policies instead
        // We'll let the actual import-snapshot call fail with a better error
        error = error1;
      }
    }

  };

  // Might be using role-based credentials, which is fine
  module.exports = PermissionsChecker;

}).call(this);
