// Generated by CoffeeScript 2.7.0
(function() {
  var SmokeTest, execSync, existsSync, join, unlinkSync, writeFileSync;

  ({execSync} = require('child_process'));

  ({writeFileSync, unlinkSync, existsSync} = require('fs'));

  ({join} = require('path'));

  // ========================================================================
  // Smoke Test - Automated validation of AMI
  // ========================================================================
  SmokeTest = class SmokeTest {
    constructor(opts1, amiId) {
      this.opts = opts1;
      this.amiId = amiId;
      this.region = this.opts.region;
      this.workDir = this.opts['work-dir'];
      this.keyName = `devuan-ami-test-${Date.now()}`;
      this.keyPath = join(this.workDir, `${this.keyName}.pem`);
      this.instanceId = null;
      this.publicIp = null;
    }

    // ====================================================================
    // Main Test Flow
    // ====================================================================
    run() {
      var error;
      console.log("\n=== Smoke Test ===");
      console.log(`  Testing AMI: ${this.amiId}`);
      console.log("");
      try {
        this.createKeyPair();
        this.launchInstance();
        this.waitForInstance();
        this.waitForCloudInit();
        this.verifySSH();
        this.verifyNetwork();
        this.verifySudo();
        console.log("\n✓ Smoke test passed!");
        console.log("  Instance is ready and fully functional");
        return true;
      } catch (error1) {
        error = error1;
        console.error(`\n✗ Smoke test failed: ${error.message}`);
        console.error("  You can investigate manually:");
        if (this.instanceId) {
          console.error(`  Instance ID: ${this.instanceId}`);
        }
        if (this.publicIp) {
          console.error(`  Public IP:   ${this.publicIp}`);
        }
        if (existsSync(this.keyPath)) {
          console.error(`  SSH key:     ${this.keyPath}`);
        }
        console.error("");
        if (this.publicIp && existsSync(this.keyPath)) {
          console.error(`  To connect: ssh -i ${this.keyPath} admin@${this.publicIp}`);
        }
        console.error("");
        return false;
      } finally {
        this.cleanup();
      }
    }

    // ====================================================================
    // Setup
    // ====================================================================
    createKeyPair() {
      var result;
      console.log("  Creating temporary SSH key pair...");
      result = execSync(`aws ec2 create-key-pair --region ${this.region} --key-name ${this.keyName} --query 'KeyMaterial' --output text`);
      writeFileSync(this.keyPath, result.toString());
      execSync(`chmod 600 ${this.keyPath}`);
      return console.log(`    ✓ Key pair created: ${this.keyName}`);
    }

    launchInstance() {
      var result, sgName, sgResult, subnetId, subnetResult, vpcId, vpcResult;
      console.log("  Launching test instance...");
      // Get default VPC
      vpcResult = execSync(`aws ec2 describe-vpcs --region ${this.region} --filters "Name=isDefault,Values=true" --query 'Vpcs[0].VpcId' --output text`, {
        encoding: 'utf8'
      });
      vpcId = vpcResult.trim();
      if (!(vpcId && vpcId !== 'None')) {
        throw new Error(`No default VPC found in ${this.region}`);
      }
      // Get default subnet
      subnetResult = execSync(`aws ec2 describe-subnets --region ${this.region} --filters "Name=vpc-id,Values=${vpcId}" "Name=default-for-az,Values=true" --query 'Subnets[0].SubnetId' --output text`, {
        encoding: 'utf8'
      });
      subnetId = subnetResult.trim();
      // Create security group for testing
      sgName = `devuan-ami-test-${Date.now()}`;
      sgResult = execSync(`aws ec2 create-security-group --region ${this.region} --group-name ${sgName} --description "Temporary security group for AMI smoke testing" --vpc-id ${vpcId} --query 'GroupId' --output text`, {
        encoding: 'utf8'
      });
      this.securityGroupId = sgResult.trim();
      // Allow SSH from anywhere (temporary test only)
      execSync(`aws ec2 authorize-security-group-ingress --region ${this.region} --group-id ${this.securityGroupId} --protocol tcp --port 22 --cidr 0.0.0.0/0`);
      // Launch instance
      result = execSync(`aws ec2 run-instances --region ${this.region} --image-id ${this.amiId} --instance-type t3.micro --key-name ${this.keyName} --security-group-ids ${this.securityGroupId} --subnet-id ${subnetId} --associate-public-ip-address --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=devuan-ami-smoke-test}]' --query 'Instances[0].InstanceId' --output text`, {
        encoding: 'utf8'
      });
      this.instanceId = result.trim();
      return console.log(`    ✓ Instance launched: ${this.instanceId}`);
    }

    // ====================================================================
    // Wait Operations
    // ====================================================================
    waitForInstance() {
      var result;
      console.log("  Waiting for instance to be running...");
      execSync(`aws ec2 wait instance-running --region ${this.region} --instance-ids ${this.instanceId}`);
      // Get public IP
      result = execSync(`aws ec2 describe-instances --region ${this.region} --instance-ids ${this.instanceId} --query 'Reservations[0].Instances[0].PublicIpAddress' --output text`, {
        encoding: 'utf8'
      });
      this.publicIp = result.trim();
      return console.log(`    ✓ Instance running at ${this.publicIp}`);
    }

    waitForCloudInit() {
      var attempt, error, maxAttempts;
      console.log("  Waiting for cloud-init to complete...");
      maxAttempts = 60;
      attempt = 0;
      while (attempt < maxAttempts) {
        try {
          // Check if cloud-init is done
          this.ssh("cloud-init status --wait --long", {
            silent: true
          });
          console.log("    ✓ Cloud-init completed");
          return;
        } catch (error1) {
          error = error1;
          // SSH might not be ready yet, or cloud-init still running
          attempt++;
          if (attempt >= maxAttempts) {
            throw new Error("Cloud-init did not complete within 5 minutes");
          }
          // Wait 5 seconds between attempts
          execSync("sleep 5");
        }
      }
    }

    // ====================================================================
    // Verification
    // ====================================================================
    verifySSH() {
      var result;
      console.log("  Verifying SSH access...");
      result = this.ssh("echo 'SSH OK'");
      if (!result.includes('SSH OK')) {
        throw new Error("SSH connection failed");
      }
      return console.log("    ✓ SSH connection works");
    }

    verifyNetwork() {
      var error, result;
      console.log("  Verifying network configuration...");
      // Check that we have a network interface with an IP
      result = this.ssh("ip addr show eth0");
      if (!result.includes('inet ')) {
        throw new Error("eth0 does not have an IP address");
      }
      try {
        // Check that we can reach the internet
        this.ssh("ping -c 1 8.8.8.8", {
          silent: true
        });
        console.log("    ✓ Network interface configured");
        return console.log("    ✓ Internet connectivity OK");
      } catch (error1) {
        error = error1;
        throw new Error("Cannot reach internet");
      }
    }

    verifySudo() {
      var result;
      console.log("  Verifying sudo access...");
      // Check that admin user can sudo
      result = this.ssh("sudo whoami");
      if (!result.includes('root')) {
        throw new Error("sudo is not working for admin user");
      }
      return console.log("    ✓ Sudo access works");
    }

    // ====================================================================
    // Cleanup
    // ====================================================================
    cleanup() {
      var error;
      console.log("\n  Cleaning up test resources...");
      // Terminate instance
      if (this.instanceId) {
        try {
          execSync(`aws ec2 terminate-instances --region ${this.region} --instance-ids ${this.instanceId}`, {
            stdio: 'ignore'
          });
          console.log(`    ✓ Instance terminated: ${this.instanceId}`);
        } catch (error1) {
          error = error1;
          console.warn(`    ⚠ Failed to terminate instance: ${this.instanceId}`);
        }
      }
      // Delete security group (after instance is terminated)
      if (this.securityGroupId) {
        try {
          // Wait a bit for instance to start terminating
          execSync("sleep 5");
          // Wait for instance to be terminated
          execSync(`aws ec2 wait instance-terminated --region ${this.region} --instance-ids ${this.instanceId}`, {
            stdio: 'ignore'
          });
          execSync(`aws ec2 delete-security-group --region ${this.region} --group-id ${this.securityGroupId}`, {
            stdio: 'ignore'
          });
          console.log("    ✓ Security group deleted");
        } catch (error1) {
          error = error1;
          console.warn(`    ⚠ Failed to delete security group: ${this.securityGroupId}`);
        }
      }
      // Delete key pair
      if (this.keyName) {
        try {
          execSync(`aws ec2 delete-key-pair --region ${this.region} --key-name ${this.keyName}`, {
            stdio: 'ignore'
          });
          console.log(`    ✓ Key pair deleted: ${this.keyName}`);
        } catch (error1) {
          error = error1;
          console.warn(`    ⚠ Failed to delete key pair: ${this.keyName}`);
        }
      }
      // Delete local key file
      if (existsSync(this.keyPath)) {
        try {
          unlinkSync(this.keyPath);
          return console.log("    ✓ Local key file deleted");
        } catch (error1) {
          error = error1;
          return console.warn(`    ⚠ Failed to delete local key file: ${this.keyPath}`);
        }
      }
    }

    // ====================================================================
    // Helpers
    // ====================================================================
    ssh(command, opts = {}) {
      var ref, result, silent, sshCmd, stdio;
      silent = (ref = opts.silent) != null ? ref : false;
      // SSH with strict host key checking disabled (this is a new host)
      sshCmd = `ssh -i ${this.keyPath} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 admin@${this.publicIp} '${command}'`;
      stdio = silent ? 'pipe' : 'inherit';
      result = execSync(sshCmd, {
        encoding: 'utf8',
        stdio: stdio
      });
      if (silent) {
        return result.toString();
      } else {
        return result;
      }
    }

  };

  module.exports = SmokeTest;

}).call(this);
