// Generated by CoffeeScript 2.7.0
(function() {
  var State, existsSync, join, mkdirSync, readFileSync, writeFileSync,
    indexOf = [].indexOf;

  ({existsSync, readFileSync, writeFileSync, mkdirSync} = require('fs'));

  ({join} = require('path'));

  // ========================================================================
  // State Management - "The filesystem is the database"
  // ========================================================================
  State = class State {
    constructor(workDir) {
      this.workDir = workDir;
      this.stateFile = join(this.workDir, '.devuan-ami-state');
      this.optionsFile = join(this.workDir, '.devuan-ami-options');
      this.state = {};
    }

    // Check if previous build exists
    exists() {
      return existsSync(this.stateFile) || existsSync(this.optionsFile);
    }

    // Load previous state
    load() {
      var content, i, key, len, line, ref, value;
      if (!this.exists()) {
        return;
      }
      // Load options
      if (existsSync(this.optionsFile)) {
        content = readFileSync(this.optionsFile, 'utf8');
        ref = content.split('\n');
        for (i = 0, len = ref.length; i < len; i++) {
          line = ref[i];
          if (!(line.trim())) {
            continue;
          }
          [key, value] = line.split('=');
          if (key) {
            this.state[key] = value;
          }
        }
      }
      // Load completed phases
      if (existsSync(this.stateFile)) {
        content = readFileSync(this.stateFile, 'utf8');
        this.state.completed = content.split('\n').filter(function(x) {
          return x.trim();
        });
      } else {
        this.state.completed = [];
      }
      return this.state;
    }

    // Save current options
    saveOptions(opts) {
      var content, existing, i, key, len, line, lines, merged, ref, value;
      mkdirSync(this.workDir, {
        recursive: true
      });
      // Load existing options to merge with
      existing = {};
      if (existsSync(this.optionsFile)) {
        content = readFileSync(this.optionsFile, 'utf8');
        ref = content.split('\n');
        for (i = 0, len = ref.length; i < len; i++) {
          line = ref[i];
          if (!(line.trim())) {
            continue;
          }
          [key, value] = line.split('=');
          if (key) {
            existing[key] = value;
          }
        }
      }
      // Merge new options with existing
      merged = Object.assign({}, existing, opts);
      lines = [];
      for (key in merged) {
        value = merged[key];
        if (key !== 'completed' && typeof value !== 'object') {
          lines.push(`${key}=${value}`);
        }
      }
      return writeFileSync(this.optionsFile, lines.join('\n'));
    }

    // Mark phase as completed
    complete(phase) {
      var base;
      if ((base = this.state).completed == null) {
        base.completed = [];
      }
      if (indexOf.call(this.state.completed, phase) < 0) {
        this.state.completed.push(phase);
      }
      return writeFileSync(this.stateFile, this.state.completed.join('\n'));
    }

    // Check if phase is completed
    isCompleted(phase) {
      var base;
      if ((base = this.state).completed == null) {
        base.completed = [];
      }
      return indexOf.call(this.state.completed, phase) >= 0;
    }

    // Get saved options
    getOptions() {
      return this.state;
    }

    // Get a specific state value
    get(key) {
      return this.state[key];
    }

    // Set a state value
    set(key, value) {
      this.state[key] = value;
      // Persist to options file (merge with existing)
      return this.saveOptions(this.state);
    }

    // Detect what's been done by checking filesystem and state file
    detectProgress() {
      var phases;
      // Check filesystem
      phases = {
        built: existsSync(join(this.workDir, 'disk.raw')) || this.isCompleted('build'),
        configured: this.isCompleted('configure'), // Trust state file for this
        converted: existsSync(join(this.workDir, 'disk.vmdk')) || this.isCompleted('convert')
      };
      return phases;
    }

  };

  module.exports = State;

}).call(this);
