// Generated by CoffeeScript 2.7.0
(function() {
  var SmokeTest, Uploader, execSync, join, readFileSync;

  ({execSync} = require('child_process'));

  ({join} = require('path'));

  ({readFileSync} = require('fs'));

  SmokeTest = require('./smoke-test');

  // ========================================================================
  // Uploader Class
  // ========================================================================
  Uploader = class Uploader {
    constructor(opts, imagePath, state) {
      this.opts = opts;
      this.imagePath = imagePath;
      this.state = state;
      this.workDir = this.opts['work-dir'];
      this.bucket = this.opts['s3-bucket'];
      this.region = this.opts.region;
      this.amiName = this.opts.name;
      this.amiId = null;
      this.vmdkPath = join(this.workDir, 'disk.vmdk');
    }

    // ====================================================================
    // Main Upload Process
    // ====================================================================
    upload() {
      var currentS3Uri, importTaskId, passed, savedS3Uri, savedTaskId, smokeTest, snapshotId;
      // Convert to VMDK streamOptimized (skip if already done)
      if (!this.state.isCompleted('convert')) {
        this.convertToVmdk();
        this.state.complete('convert');
      } else {
        console.log("  Converting to VMDK streamOptimized... (skipped, already done)");
      }
      // Upload to S3 (skip if already done and URI matches)
      savedS3Uri = this.state.get('s3-uri');
      currentS3Uri = this.generateS3Uri();
      if (this.state.isCompleted('upload') && savedS3Uri === currentS3Uri) {
        console.log("  Uploading to S3... (skipped, already uploaded)");
        this.s3Uri = savedS3Uri;
        this.s3Key = this.state.get('s3-key');
      } else {
        this.uploadToS3();
        this.state.set('s3-uri', this.s3Uri);
        this.state.set('s3-key', this.s3Key);
        this.state.complete('upload');
      }
      // Import snapshot (resume if interrupted)
      savedTaskId = this.state.get('import-task-id');
      if (savedTaskId && this.state.isCompleted('import-started')) {
        console.log(`  Resuming import snapshot task: ${savedTaskId}`);
        importTaskId = savedTaskId;
      } else {
        importTaskId = this.importSnapshot();
        this.state.set('import-task-id', importTaskId);
        this.state.complete('import-started');
      }
      snapshotId = this.waitForImport(importTaskId);
      this.state.set('snapshot-id', snapshotId);
      this.state.complete('import');
      // Register AMI
      this.amiId = this.registerAMI(snapshotId);
      this.state.set('ami-id', this.amiId);
      this.state.complete('register');
      // Run smoke test
      if (!this.state.isCompleted('smoke-test')) {
        smokeTest = new SmokeTest(this.opts, this.amiId);
        passed = smokeTest.run();
        if (passed) {
          this.state.complete('smoke-test');
        } else {
          console.warn("\n⚠ Smoke test failed, but AMI was created successfully");
          console.warn(`  AMI ID: ${this.amiId}`);
          console.warn("  You may want to investigate and fix issues before using this AMI");
        }
      } else {
        console.log("\n=== Smoke Test ===");
        console.log("  Smoke test already passed for this AMI");
      }
      this.cleanup();
      return this.amiId;
    }

    // ====================================================================
    // Upload Steps
    // ====================================================================
    generateS3Uri() {
      var s3Key;
      s3Key = `devuan-ami-imports/${this.amiName}.vmdk`;
      return `s3://${this.bucket}/${s3Key}`;
    }

    convertToVmdk() {
      console.log("  Converting to VMDK streamOptimized format...");
      return execSync(`qemu-img convert -f raw -O vmdk -o subformat=streamOptimized ${this.imagePath} ${this.vmdkPath}`);
    }

    uploadToS3() {
      // Use deterministic S3 key (no timestamp) so we can detect re-uploads
      this.s3Key = `devuan-ami-imports/${this.amiName}.vmdk`;
      this.s3Uri = `s3://${this.bucket}/${this.s3Key}`;
      console.log(`  Uploading VMDK to S3: ${this.s3Uri}`);
      return execSync(`aws s3 cp ${this.vmdkPath} ${this.s3Uri} --region ${this.region}`);
    }

    importSnapshot() {
      var cmd, containerFile, diskContainer, importTaskId, output, result, writeFileSync;
      console.log("  Creating import snapshot task...");
      // Create disk container JSON for import
      diskContainer = {
        Description: this.amiName,
        Format: 'VMDK',
        UserBucket: {
          S3Bucket: this.bucket,
          S3Key: this.s3Key
        }
      };
      // Write to temp file
      containerFile = join(this.workDir, 'container.json');
      ({writeFileSync} = require('fs'));
      writeFileSync(containerFile, JSON.stringify(diskContainer));
      // Import snapshot
      cmd = `aws ec2 import-snapshot --region ${this.region} --description "${this.amiName}" --disk-container file://${containerFile}`;
      output = execSync(cmd);
      result = JSON.parse(output.toString());
      importTaskId = result.ImportTaskId;
      console.log(`  Import task ID: ${importTaskId}`);
      return importTaskId;
    }

    waitForImport(taskId) {
      var cmd, detail, errorMsg, message, output, progress, result, snapshotId, status, task;
      console.log("  Waiting for import to complete (this may take 10-30 minutes)...");
      while (true) {
        // Check status
        cmd = `aws ec2 describe-import-snapshot-tasks --region ${this.region} --import-task-ids ${taskId}`;
        output = execSync(cmd);
        result = JSON.parse(output.toString());
        task = result.ImportSnapshotTasks[0];
        detail = task.SnapshotTaskDetail;
        status = detail.Status;
        progress = detail.Progress || '0';
        console.log(`  Import progress: ${progress}% (${status})`);
        if (status === 'completed') {
          snapshotId = detail.SnapshotId;
          console.log(`  Snapshot created: ${snapshotId}`);
          return snapshotId;
        }
        if (status === 'deleted' || status === 'deleting') {
          errorMsg = detail.StatusMessage || 'No error message provided';
          throw new Error(`Import task was deleted: ${errorMsg}`);
        }
        if (detail.StatusMessage) {
          message = detail.StatusMessage;
          console.log(`  Status: ${message}`);
          if (message.includes('error') || message.includes('fail')) {
            throw new Error(`Import failed: ${message}`);
          }
        }
        // Wait 30 seconds before checking again
        execSync('sleep 30');
      }
    }

    registerAMI(snapshotId) {
      var amiId, arch, awsArch, cmd, output, result, rootDevice;
      console.log("  Registering AMI from snapshot...");
      arch = this.opts.arch;
      awsArch = arch === 'amd64' ? 'x86_64' : 'arm64';
      // Determine root device name based on architecture
      rootDevice = '/dev/sda1';
      cmd = `aws ec2 register-image --region ${this.region} --name "${this.amiName}" --description "Devuan ${this.opts.release} ${arch}" --architecture ${awsArch} --root-device-name ${rootDevice} --virtualization-type hvm --ena-support --block-device-mappings '[{
		"DeviceName": "${rootDevice}",
		"Ebs": {
			"SnapshotId": "${snapshotId}",
			"VolumeType": "gp3",
			"DeleteOnTermination": true
		}
	}]'`;
      output = execSync(cmd);
      result = JSON.parse(output.toString());
      amiId = result.ImageId;
      console.log(`  AMI registered: ${amiId}`);
      return amiId;
    }

    cleanup() {
      var error;
      console.log("  Cleaning up local temporary files...");
      try {
        // Remove VMDK file
        execSync(`rm -f ${this.vmdkPath}`);
        return console.log("  Removed local VMDK file");
      } catch (error1) {
        error = error1;
        return console.warn(`  Warning: Failed to remove ${this.vmdkPath}`);
      }
    }

  };

  // Note: Keeping S3 object for manual cleanup (lifecycle policy will delete after 7 days)
  module.exports = Uploader;

}).call(this);
